version: '3'
services:
  postgres:
    image: postgres:13
    container_name: mi_data_warehouse
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ventas_db
    ports:
      - "5434:5432"  